name: 'Helm values merger'
description: 'Merge values files for Helm charts'
author: 'Creatiwity'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  secrets:
    description: 'Secrets'
    required: false

# Define your outputs here.
#outputs:
# time:
#  description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
